// <auto-generated />
using System;
using LottyAB.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LottyAB.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LottyAB.Domain.Entities.ApproverGroupEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ApproversToStart")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("ApproverGroups");
                });

            modelBuilder.Entity("LottyAB.Domain.Entities.DecisionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ExperimentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FeatureFlagId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<string>("SubjectAttributesJson")
                        .HasColumnType("text");

                    b.Property<string>("SubjectId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("VariantId")
                        .HasColumnType("uuid");

                    b.Property<string>("VariantValue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FeatureFlagId");

                    b.HasIndex("VariantId");

                    b.HasIndex("ExperimentId", "Timestamp");

                    b.ToTable("Decisions");
                });

            modelBuilder.Entity("LottyAB.Domain.Entities.EventEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DecisionId")
                        .HasColumnType("uuid");

                    b.Property<string>("EventId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("EventTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EventTypeId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsAttributed")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDuplicate")
                        .HasColumnType("boolean");

                    b.Property<string>("PropertiesJson")
                        .HasColumnType("text");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("text");

                    b.Property<string>("SubjectId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DecisionId");

                    b.HasIndex("EventId")
                        .IsUnique();

                    b.HasIndex("EventTypeId");

                    b.HasIndex("IsAttributed", "EventTimestamp");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("LottyAB.Domain.Entities.EventTypeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EventKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsExposureEvent")
                        .HasColumnType("boolean");

                    b.Property<string>("RequiredPropertiesJson")
                        .HasColumnType("text");

                    b.Property<bool>("RequiresExposure")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("EventKey")
                        .IsUnique();

                    b.ToTable("EventTypes");
                });

            modelBuilder.Entity("LottyAB.Domain.Entities.ExperimentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ApproverGroupId")
                        .HasColumnType("uuid");

                    b.Property<double>("AudienceFraction")
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ConflictDomains")
                        .HasColumnType("text");

                    b.Property<int?>("ConflictPolicy")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid>("FeatureFlagId")
                        .HasColumnType("uuid");

                    b.Property<string>("GuardrailMetricKeys")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("Outcome")
                        .HasColumnType("integer");

                    b.Property<string>("OutcomeComment")
                        .HasColumnType("text");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<string>("PrimaryMetricKey")
                        .HasColumnType("text");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("TargetingRule")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ApproverGroupId");

                    b.HasIndex("OwnerId");

                    b.HasIndex("FeatureFlagId", "Status");

                    b.ToTable("Experiments");
                });

            modelBuilder.Entity("LottyAB.Domain.Entities.ExperimentReviewEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Decision")
                        .HasColumnType("integer");

                    b.Property<Guid>("ExperimentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ReviewerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ExperimentId");

                    b.HasIndex("ReviewerId");

                    b.ToTable("ExperimentReviews");
                });

            modelBuilder.Entity("LottyAB.Domain.Entities.ExperimentVersionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("AudienceFraction")
                        .HasColumnType("double precision");

                    b.Property<string>("ChangeReason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ChangedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid>("ExperimentId")
                        .HasColumnType("uuid");

                    b.Property<string>("GuardrailMetricKeys")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PrimaryMetricKey")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("TargetingRule")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VariantsSnapshot")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ExperimentId");

                    b.ToTable("ExperimentVersions");
                });

            modelBuilder.Entity("LottyAB.Domain.Entities.FeatureFlagEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DefaultValue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ValueType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("FeatureFlags");
                });

            modelBuilder.Entity("LottyAB.Domain.Entities.GuardrailEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Action")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ExperimentId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("MetricKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ObservationWindowMinutes")
                        .HasColumnType("integer");

                    b.Property<double>("Threshold")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ExperimentId");

                    b.ToTable("Guardrails");
                });

            modelBuilder.Entity("LottyAB.Domain.Entities.GuardrailTriggerHistoryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ActionTaken")
                        .HasColumnType("integer");

                    b.Property<double>("ActualValue")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ExperimentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GuardrailId")
                        .HasColumnType("uuid");

                    b.Property<string>("MetricKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ObservationWindowMinutes")
                        .HasColumnType("integer");

                    b.Property<double>("Threshold")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("TriggeredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ExperimentId");

                    b.HasIndex("GuardrailId");

                    b.ToTable("GuardrailTriggerHistory");
                });

            modelBuilder.Entity("LottyAB.Domain.Entities.MetricDefinitionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AggregationType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EventTypeKeys")
                        .HasColumnType("text");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<string>("MetricKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("MetricDefinitions");
                });

            modelBuilder.Entity("LottyAB.Domain.Entities.RampPlanEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CurrentStepIndex")
                        .HasColumnType("integer");

                    b.Property<Guid>("ExperimentId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<int>("MinImpressionsPerStep")
                        .HasColumnType("integer");

                    b.Property<int>("MinMinutesPerStep")
                        .HasColumnType("integer");

                    b.Property<int>("SafetyAction")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StepEnteredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("StepsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ExperimentId")
                        .IsUnique();

                    b.ToTable("RampPlans");
                });

            modelBuilder.Entity("LottyAB.Domain.Entities.RampPlanHistoryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Action")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ExperimentId")
                        .HasColumnType("uuid");

                    b.Property<double>("FromFraction")
                        .HasColumnType("double precision");

                    b.Property<Guid>("RampPlanId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("ToFraction")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("RampPlanId");

                    b.ToTable("RampPlanHistory");
                });

            modelBuilder.Entity("LottyAB.Domain.Entities.SubjectParticipationEntity", b =>
                {
                    b.Property<string>("SubjectId")
                        .HasColumnType("text");

                    b.Property<Guid>("ExperimentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ParticipatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("SubjectId", "ExperimentId");

                    b.HasIndex("SubjectId", "ParticipatedAt");

                    b.ToTable("SubjectParticipation");
                });

            modelBuilder.Entity("LottyAB.Domain.Entities.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ApproverGroupEntityId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ApproverGroupEntityId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("LottyAB.Domain.Entities.VariantEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid>("ExperimentId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsControl")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Weight")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("ExperimentId");

                    b.ToTable("Variants");
                });

            modelBuilder.Entity("LottyAB.Domain.Entities.DecisionEntity", b =>
                {
                    b.HasOne("LottyAB.Domain.Entities.ExperimentEntity", "Experiment")
                        .WithMany()
                        .HasForeignKey("ExperimentId");

                    b.HasOne("LottyAB.Domain.Entities.FeatureFlagEntity", "FeatureFlag")
                        .WithMany()
                        .HasForeignKey("FeatureFlagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LottyAB.Domain.Entities.VariantEntity", "Variant")
                        .WithMany()
                        .HasForeignKey("VariantId");

                    b.Navigation("Experiment");

                    b.Navigation("FeatureFlag");

                    b.Navigation("Variant");
                });

            modelBuilder.Entity("LottyAB.Domain.Entities.EventEntity", b =>
                {
                    b.HasOne("LottyAB.Domain.Entities.DecisionEntity", "Decision")
                        .WithMany()
                        .HasForeignKey("DecisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LottyAB.Domain.Entities.EventTypeEntity", "EventType")
                        .WithMany("Events")
                        .HasForeignKey("EventTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Decision");

                    b.Navigation("EventType");
                });

            modelBuilder.Entity("LottyAB.Domain.Entities.ExperimentEntity", b =>
                {
                    b.HasOne("LottyAB.Domain.Entities.ApproverGroupEntity", "ApproverGroup")
                        .WithMany()
                        .HasForeignKey("ApproverGroupId");

                    b.HasOne("LottyAB.Domain.Entities.FeatureFlagEntity", "FeatureFlag")
                        .WithMany("Experiments")
                        .HasForeignKey("FeatureFlagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LottyAB.Domain.Entities.UserEntity", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApproverGroup");

                    b.Navigation("FeatureFlag");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("LottyAB.Domain.Entities.ExperimentReviewEntity", b =>
                {
                    b.HasOne("LottyAB.Domain.Entities.ExperimentEntity", "Experiment")
                        .WithMany("Reviews")
                        .HasForeignKey("ExperimentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LottyAB.Domain.Entities.UserEntity", "Reviewer")
                        .WithMany()
                        .HasForeignKey("ReviewerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Experiment");

                    b.Navigation("Reviewer");
                });

            modelBuilder.Entity("LottyAB.Domain.Entities.ExperimentVersionEntity", b =>
                {
                    b.HasOne("LottyAB.Domain.Entities.ExperimentEntity", "Experiment")
                        .WithMany("Versions")
                        .HasForeignKey("ExperimentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Experiment");
                });

            modelBuilder.Entity("LottyAB.Domain.Entities.GuardrailEntity", b =>
                {
                    b.HasOne("LottyAB.Domain.Entities.ExperimentEntity", "Experiment")
                        .WithMany("Guardrails")
                        .HasForeignKey("ExperimentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Experiment");
                });

            modelBuilder.Entity("LottyAB.Domain.Entities.GuardrailTriggerHistoryEntity", b =>
                {
                    b.HasOne("LottyAB.Domain.Entities.ExperimentEntity", "Experiment")
                        .WithMany("GuardrailTriggers")
                        .HasForeignKey("ExperimentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LottyAB.Domain.Entities.GuardrailEntity", "Guardrail")
                        .WithMany("TriggerHistory")
                        .HasForeignKey("GuardrailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Experiment");

                    b.Navigation("Guardrail");
                });

            modelBuilder.Entity("LottyAB.Domain.Entities.RampPlanEntity", b =>
                {
                    b.HasOne("LottyAB.Domain.Entities.ExperimentEntity", "Experiment")
                        .WithOne("RampPlan")
                        .HasForeignKey("LottyAB.Domain.Entities.RampPlanEntity", "ExperimentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Experiment");
                });

            modelBuilder.Entity("LottyAB.Domain.Entities.RampPlanHistoryEntity", b =>
                {
                    b.HasOne("LottyAB.Domain.Entities.RampPlanEntity", "RampPlan")
                        .WithMany("History")
                        .HasForeignKey("RampPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RampPlan");
                });

            modelBuilder.Entity("LottyAB.Domain.Entities.UserEntity", b =>
                {
                    b.HasOne("LottyAB.Domain.Entities.ApproverGroupEntity", null)
                        .WithMany("Approvers")
                        .HasForeignKey("ApproverGroupEntityId");
                });

            modelBuilder.Entity("LottyAB.Domain.Entities.VariantEntity", b =>
                {
                    b.HasOne("LottyAB.Domain.Entities.ExperimentEntity", "Experiment")
                        .WithMany("Variants")
                        .HasForeignKey("ExperimentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Experiment");
                });

            modelBuilder.Entity("LottyAB.Domain.Entities.ApproverGroupEntity", b =>
                {
                    b.Navigation("Approvers");
                });

            modelBuilder.Entity("LottyAB.Domain.Entities.EventTypeEntity", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("LottyAB.Domain.Entities.ExperimentEntity", b =>
                {
                    b.Navigation("GuardrailTriggers");

                    b.Navigation("Guardrails");

                    b.Navigation("RampPlan");

                    b.Navigation("Reviews");

                    b.Navigation("Variants");

                    b.Navigation("Versions");
                });

            modelBuilder.Entity("LottyAB.Domain.Entities.FeatureFlagEntity", b =>
                {
                    b.Navigation("Experiments");
                });

            modelBuilder.Entity("LottyAB.Domain.Entities.GuardrailEntity", b =>
                {
                    b.Navigation("TriggerHistory");
                });

            modelBuilder.Entity("LottyAB.Domain.Entities.RampPlanEntity", b =>
                {
                    b.Navigation("History");
                });
#pragma warning restore 612, 618
        }
    }
}
